---
- name: reload systemd
  systemd:
    daemon_reload: yes

- name: enforce kafka permissions
  file:
    path: "{{ kafka_path }}"
    state: directory
    owner: kafka
    group: kafka
    mode: 0750
    recurse: yes
    
- name: restart kafka service
  systemd:
    name: confluent-server
    state: restarted